# Generated by Django 5.1.7 on 2025-05-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='needs_support',
            field=models.BooleanField(default=False),
        ),
    ]
