# Generated by Django 5.1.7 on 2025-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_comment_is_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xử lý'), ('processing', 'Đang xử lý'), ('delayed', 'Tạm hoãn'), ('resolved', 'Đã xử lý')], default='pending', max_length=20),
        ),
    ]
